language: haskell

sudo: false
cache:
  directories:
    - $HOME/.stack/

branches:
  only:
    - src

env:
  global:
    - GH_NAME="335g.travis"
    - secure: "hByayKJ4Dc8xTLJu3Vz3wYZCz0O67ueWfUr8JPXqApI1vc7aS4XhFsinGuqFvf6Pb4PSVT0qOC6fSLNVcucxsMD+7ixT7lUCjZ5a6jLDFkpX8GaDyqYCGOgMziFAqow/GXeVAuT3A2VOJ6oVpghOHq0MIzOdpNZ7KCG34dGvH22gmB6vlZQhOt//A2yIFzFetP6Zkr0ccm9Riq4Lkic5GHZ2D8BTFsgQO+yl95y690Ej6GV6kMPwCVKHbVGShDI1qP97F84I2iojVyzK5jTvJxQLPYZoluxLuAWYk8FYZqvJI4ShguZyPlIBrwIjmGLVDNvPpJxgBKvPWbtHdG/vo4E/Ubgpa0isC+WY9bJuFKm/lFSwukHs2iQcsdae6PhsFlTfAh6L4w73y60M27mRTSUjYwBBVhKRiisMWjpRzw0h/GCBm3bCjirtpCeAIUbtW19nQ+PRvlUqvjNcDLnT4xCz9V7YrZ41bRoIhBGWNqcSvYrj05o6GKHdgA3QY5gnn1HBAFGJvOm9mmstoUs++ant9fE5icdXiaVF5BaGvO3vYyY/W7Ynr15PeTt/LAYjd9rYVKdP216LS0jWqX7JJQayL+rDucftPR62bOmLJEKoimrwKOBaHRaqz/t6eZDH2w+VlO8K//UAvbGyuVrWxPaP0BfnOU7K/8qnNSeAgxI="
    - secure: "R+qKNt+hM6wiKbIt/5euAV2r8p4t4Ajbpk017oC3SeF6kDV6BYeI4Jvd2OoL3RE2bTcAaGiPVTp29LlCETSiN4DOe46uCVX0UMlo30EZgZN51xZ9Ig14rHdIvdCLLI1FSXzBjSCbTn/hBcUpjQKjR1Gp8CyIJ0ZCooxicwbFXq3GDD6QeSsCT6ROM40UKcBXwmcFsyPkAD9PQES0uwqNBPcokW4vnQp35ZHu9Yu3SVKa8zfb5oiAAjKnkoA0TaWjF5PXui8cuwsEdKs1AZnKaz07jbxm/y2+38H+ONkrmY8xbN72Wm59wkP5p2FU7qRB2K1EfFaknl/UGRkgC01mBvHCI6PxJDDQlhITDBx8aw1vXjtmbIXRC4Ndg4EY2TM05JuAOGxtSTOPKgjiu3205DwOPpyquoo/BuRnIqnnW5pNPuzzuhyfb6VwKnYw9gHDVjGNgkkFl6Jf7klIJCI/6aZ7QwxrBLJq3jBDe1oVflHA4/QFFNsQe4R0pMeNNLhl8jg+f8P0lFrgLcX73DP5Z17+9WlpwPkmsSxuv+Rk696FpPrw7JwaymquZQOQHluoRQBqF85nAvM4fzGtA1ohWohacdc4g3X12NPOoj96rnf2T3+zX8vyiqfUhWP+Gq7R0cgah1fyCEgImvcT1YxUmcFdBFbDvmQlfFzpubmaPpo="

before_install:
  - mkdir -p ~/.local/bin
  - export PATH=~/.local/bin:$PATH
  - travis_retry curl -L https://github.com/commercialhaskell/stack/releases/download/v0.1.2.0/stack-0.1.2.0-x86_64-linux.gz | gunzip > ~/.local/bin/stack
  - chmod a+x ~/.local/bin/stack
  - export PATH=~/opt/ghc/7.8.4/bin:$PATH
  - git submodule foreach --recursive 'git checkout master; git ls-files | grep -v README | grep -v CNAME | xargs -r git rm'

addons:
  apt:
    sources:
      - hvr-ghc
    packages:
      - ghc-7.8.4

install:
  - travis_wait
  - stack setup --no-terminal
  - stack build --only-snapshot --no-terminal

before_script:
  - git config --global user.name "$GH_NAME"
  - git config --global user.email "$GH_EMAIL"

script:
  - stack build --no-terminal
  - cd weblog
  - stack ghc site.hs
  - ./site build

after_success:
  - cd _site
  - export REMOTE=$(git config remote.origin.url | sed 's/.*:\/\///')
  - git remote add github https://${GH_TOKEN}@${REMOTE}
  - git add ./*
  - git status
  - git commit -m "Built by Travis (build $TRAVIS_BUILD_NUMBER)"
  - git push --quiet github master:master

notifications:
  email: false
